# Generated by Django 4.2.29 on 2026-04-01 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpinnerPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('spinner_type', models.CharField(choices=[('name', 'Name Spinner'), ('number', 'Number Spinner'), ('custom', 'Custom Spinner'), ('yesno', 'Yes/No Spinner'), ('color', 'Color Spinner')], default='custom', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SpinnerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('color', models.CharField(default='#FF6384', max_length=7)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='spinners.spinnerpreset')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=200)),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='spinners.spinnerpreset')),
            ],
            options={
                'verbose_name_plural': 'Spin histories',
                'ordering': ['-spun_at'],
            },
        ),
    ]
